### ISSUE TITLE
Release on Grafana Dashboards with collaborative account

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/grafana-dashboard#11]
There is no possibility to share access on dashboard edit and publish in Grafana Official and community built dashboards now. We need to create come kind of collaborative account to make it able to edit and upload new versions of dashboard with our team.

**Comment by DifferentialOrange** [comment]
Since it seems that there is no way to transfer dashboard ownership (I never discussed it with Grafana support, maybe it worth trying), new dashboard page should be created and panel with deprecation message and link to a new dashboard should be added to current dashboard.

**Comment by Totktonada** [comment]
It is better to ask support for suggestions first. I'm sure we're not alone with this problem.

**Comment by DifferentialOrange** [comment]
Thanks to new Organization feature I've been able to migrate dashboard ownership to admin@tarantool.org account. Credentials are available at team storage.
