### ISSUE TITLE
Add some illustrations and descriptions

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/grafana-dashboard#2]
The dashboard should be described somewhere. It is needed to compile the board now to get what it consists of or read through the code. The description should be illustrated with screenshots.

**Comment by DifferentialOrange** [comment]
Partially closed in #7, but some illustration should be also added to README.

**Comment by Totktonada** [comment]
My expectation from README is to give me steps how to get nice counters having a tarantool instance: what I should run inside tarantool, what I should install and setup outside it.

**Comment by DifferentialOrange** [comment]
@Totktonada It's described on Grafana page: https://grafana.com/grafana/dashboards/12567 (to be honest, it's a bit outdated since introducing of _cartridge.roles.metrics_ role, but still works), maybe I should duplicate it here or at least explicitly say that instruction can be found on Grafana page.

**Comment by DifferentialOrange** [comment]
Updated Grafana page guide on Tarantool setup with _cartridge.roles.metrics_ info, added "How to use" section with explicit reference to Grafana page.

**Comment by Totktonada** [comment]
Thank you!

**Comment by DifferentialOrange** [comment]
Some illustration was added in #50, I think thus we can close this ticket
