### ISSUE TITLE
Build dashboard with pre-defined data source

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/grafana-dashboard#90]
It's impossible to build json with fixed datasource since all dashboards choose target type based on template variable value 
https://github.com/tarantool/grafana-dashboard/blob/845e88c39b1c0c87de994984ba14ecac653857f4/dashboard/common.libsonnet#L75-L88

If someone decides to build compiled dashboard with `myinflux` datasource, it won't work out.

**Comment by opomuc** [comment]
@DifferentialOrange 

On a side note... Can we actually build dashboard for our private projects? changing `Datasource` to some our predefined value?

**Comment by DifferentialOrange** [comment]
> @DifferentialOrange
> 
> On a side note... Can we actually build dashboard for our private projects? changing `Datasource` to some our predefined value?

Now you can manually replace all `${DS_PROMETHEUS}` with required value (and also you can [remove DS_PROMETHEUS variable](https://github.com/tarantool/grafana-dashboard/blob/184bc6f7bdd5c83d684555986fb2296d66fa921c/tests/Prometheus/dashboard_compiled.json#L3-L10)). After resolving this ticket it should be better.
